version: '3.8'

services:
  # Vosk ASR Server for voicemail detection
  vosk-server:
    image: lacerovasq/voicemail
    container_name: ${VOSK_CONTAINER_NAME:-vosk-asr-server}
    ports:
      - "${VOSK_PORT:-2700}:2700"
      - "2800:2800"
    networks:
      - voicemail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2700"] 
      interval: 30s
      timeout: 10s
      retries: 3

  # FreeSWITCH with Voicemail Detection
  freeswitch:
    build:
      context: ./docker
      dockerfile: Dockerfile.optimized
      args:
        - EXTERNAL_IP=${FREESWITCH_EXTERNAL_IP:-192.168.1.100}
    container_name: ${FREESWITCH_CONTAINER_NAME:-freeswitch-voicemail-detector}
    volumes:
      - ./conf/:/usr/local/freeswitch/conf/
      - ./scripts/:/usr/local/freeswitch/scripts/
      - ./logs/:/var/log/freeswitch/
      - voicemail_recordings:/tmp/recordings/
    ports:
      - "${FREESWITCH_SIP_PORT:-5060}:5060/udp"   # SIP UDP
      - "${FREESWITCH_SIP_PORT:-5060}:5060/tcp"   # SIP TCP  
      - "${FREESWITCH_EVENT_SOCKET_PORT:-8021}:8021/tcp"   # Event Socket (fs_cli)
      - "${FREESWITCH_RTP_START:-16384}-${FREESWITCH_RTP_END:-16500}:${FREESWITCH_RTP_START:-16384}-${FREESWITCH_RTP_END:-16500}/udp"  # RTP
    environment:
      - FREESWITCH_EXTERNAL_IP=${FREESWITCH_EXTERNAL_IP:-192.168.1.100}
      - GATEWAY_HOST=${GATEWAY_HOST:-172.16.250.197}
      - GATEWAY_USERNAME=${GATEWAY_USERNAME:-77751}
      - GATEWAY_PASSWORD=${GATEWAY_PASSWORD:-77751}
      - VOSK_HOST=${VOSK_HOST:-vosk-server}
      - VOSK_PORT=${VOSK_PORT:-2700}
      - DETECTION_CONFIDENCE_THRESHOLD=${DETECTION_CONFIDENCE_THRESHOLD:-80}
    networks:
      - voicemail-network
    depends_on:
      - vosk-server
    restart: unless-stopped
    # Security capabilities for better performance (optional)
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    ulimits:
      memlock: -1
      stack: 8192
    healthcheck:
      test: ["CMD", "/usr/local/freeswitch/bin/fs_cli", "-x", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  voicemail_recordings:
    driver: local

networks:
  voicemail-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16